pipeline:
    name: onlineboutique
    identifier: onlineboutique
    projectIdentifier: Online_Boutique
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.Github
                repoName: onlineboutique
                build: <+input>
    stages:
        - parallel:
              - stage:
                    name: Go Unit Tests
                    identifier: Go_Unit_Tests
                    type: CI
                    spec:
                        cloneCodebase: true
                        infrastructure:
                            type: KubernetesDirect
                            spec:
                                connectorRef: account.GKE
                                namespace: harness-builds
                                automountServiceAccountToken: true
                                nodeSelector: {}
                                os: Linux
                        execution:
                            steps:
                                - step:
                                      type: Run
                                      name: Unit Tests
                                      identifier: Unit_Tests
                                      spec:
                                          connectorRef: account.harnessImage
                                          image: golang:<+stage.variables.goVersion>
                                          shell: Sh
                                          command: |-
                                              go install gotest.tools/gotestsum@latest
                                              cd src/<+matrix.service>
                                              gotestsum --junitfile unit-tests-<+matrix.service>.xml
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/unit-tests-<+matrix.service>.xml"
                                      failureStrategies: []
                                      strategy:
                                          matrix:
                                              service:
                                                  - shippingservice
                                                  - productcatalogservice
                    variables:
                        - name: goVersion
                          type: String
                          value: 1.17.5
              - stage:
                    name: CSharp Unit Tests
                    identifier: CSharp_Unit_Tests
                    type: CI
                    spec:
                        cloneCodebase: true
                        infrastructure:
                            type: VM
                            spec:
                                type: Pool
                                spec:
                                    poolName: windows
                                    os: Windows
                        execution:
                            steps:
                                - step:
                                      type: RunTests
                                      name: Unit Tests
                                      identifier: Unit_Tests
                                      spec:
                                          language: Csharp
                                          buildEnvironment: Core
                                          frameworkVersion: "6.0"
                                          buildTool: Dotnet
                                          args: src/cartservice/
                                          runOnlySelectedTests: true
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                    when:
                        pipelineStatus: Success
              - stage:
                    name: Security Tests
                    identifier: Security_Tests
                    type: SecurityTests
                    spec:
                        cloneCodebase: true
                        infrastructure:
                            useFromStage: Go_Unit_Tests
                        execution:
                            steps:
                                - step:
                                      type: Security
                                      name: OWASP
                                      identifier: OWASP
                                      spec:
                                          connectorRef: account.harnessImage
                                          privileged: true
                                          settings:
                                              policy_type: orchestratedScan
                                              scan_type: repository
                                              product_name: owasp
                                              product_config_name: default
                        serviceDependencies:
                            - identifier: DIND
                              name: DIND
                              type: Service
                              spec:
                                  connectorRef: account.harnessImage
                                  image: docker:dind
                                  privileged: true
                        sharedPaths:
                            - /var/run
                            - /var/lib/docker
    allowStageExecutions: true
