pipeline:
    name: onlineboutique
    identifier: onlineboutique
    projectIdentifier: Online_Boutique
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.Github
                repoName: onlineboutique
                build: <+input>
    stages:
        - stage:
              name: Go Unit Tests
              identifier: Go_Unit_Tests
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.GKE
                          namespace: harness-builds
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Unit Tests
                                identifier: Unit_Tests
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+stage.variables.goVersion>
                                    shell: Sh
                                    command: |-
                                        ls
                                        go test src/<+matrix.service>
              variables:
                  - name: goVersion
                    type: String
                    value: 1.17.5
              strategy:
                  matrix:
                      service:
                          - shippingservice
                          - productcatalogservice
